Add custom trigger examples
chamaeleonidae/api pull request #31
Opened 2023-06-30 14:15 UTC by shaggun

Add custom trigger examples

2023-06-30 14:15 UTC, shaggun commented
![](https://github.trello.services/images/mini-trello-icon.png) [New On-page Triggers Actions (2/3) - Custom Trigger](https://trello.com/c/p0nxOQVY/4569-new-on-page-triggers-actions-2-3-custom-trigger)

2023-07-03 14:59 UTC, bnorton requested changes
I think there are still a couple examples / use cases missing.

0. 1-2 more where the code directly evaluates to true/false without Promises
1. Calculation of true/false based on 2-3 aspects of user data
2. User data + DOM state
3. Use of Promise + setInterval to watch for a state in the DOM
4. Use of Promise + click listener

2023-07-03 14:59 UTC, bnorton commented on docs/concepts/custom-triggers.md
> +fetch('https://jsonplaceholder.typicode.com/todos/x')
```suggestion
fetch('https://jsonplaceholder.typicode.com/todos/not-an-id')
```

2023-07-03 14:59 UTC, bnorton commented on docs/concepts/custom-triggers.md
> +return age > 18;
```suggestion
const input = document.getElementById('user-age');
const age = parseInt(input.value) || 0;

age > 18
```

2023-07-03 14:59 UTC, bnorton commented on docs/concepts/custom-triggers.md
> +promise
```suggestion
new Promise((resolve, reject) => {
  setTimeout(() => { resolve("Display"); }, 5000);
});
```

2023-07-03 14:59 UTC, bnorton commented on docs/concepts/custom-triggers.md
> +promise
```suggestion
new Promise((resolve, reject) => {
  setTimeout(() => { reject(true); }, 5000);
});
```

2023-07-04 20:31 UTC, shaggun commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add custom trigger examples to API page](https://trello.com/c/vVkc3noi/4646-add-custom-trigger-examples-to-api-page)

2023-07-11 03:08 UTC, bnorton approved these changes
looking good!

2023-07-11 13:30 UTC, merged